<a href="https://colab.research.google.com/github/dsnato/imersao-dados-python/blob/main/aulas_imersao_dados_python_alura.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Aula 01 - Explorando Dados com Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv')

In [ ]:
df.head(10)

work_year experience_level employment_type           job_title  salary  \
0     2025.0               SE              FT  Solutions Engineer  214000   
1     2025.0               SE              FT  Solutions Engineer  136000   
2     2025.0               MI              FT       Data Engineer  158800   
3     2025.0               MI              FT       Data Engineer  139200   
4     2025.0               EN              FT       Data Engineer   90000   
5     2025.0               EN              FT       Data Engineer   80000   
6     2025.0               SE              FT      Data Scientist  185000   
7     2025.0               SE              FT      Data Scientist  148000   
8     2025.0               MI              FT      Data Scientist  135000   
9     2025.0               MI              FT      Data Scientist  108000   

  salary_currency  salary_in_usd employee_residence  remote_ratio  \
0             USD         214000                 US           100   
1             USD         136000                 US           100   
2             USD         158800                 AU             0   
3             USD         139200                 AU             0   
4             USD          90000                 US             0   
5             USD          80000                 US             0   
6             USD         185000                 US             0   
7             USD         148000                 US             0   
8             USD         135000                 CA             0   
9             USD         108000                 CA             0   

  company_location company_size  
0               US            M  
1               US            M  
2               AU            M  
3               AU            M  
4               US            M  
5               US            M  
6               US            M  
7               US            M  
8               CA            M  
9               CA            M

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133349 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype  
---  ------              --------------   -----  
 0   work_year           133339 non-null  float64
 1   experience_level    133349 non-null  object 
 2   employment_type     133349 non-null  object 
 3   job_title           133349 non-null  object 
 4   salary              133349 non-null  int64  
 5   salary_currency     133349 non-null  object 
 6   salary_in_usd       133349 non-null  int64  
 7   employee_residence  133349 non-null  object 
 8   remote_ratio        133349 non-null  int64  
 9   company_location    133349 non-null  object 
 10  company_size        133349 non-null  object 
dtypes: float64(1), int64(3), object(7)
memory usage: 11.2+ MB


In [ ]:
df.describe()

work_year        salary  salary_in_usd   remote_ratio
count  133339.000000  1.333490e+05  133349.000000  133349.000000
mean     2024.358770  1.632833e+05  157617.272098      20.905669
std         0.680627  2.173860e+05   74288.363097      40.590044
min      2020.000000  1.400000e+04   15000.000000       0.000000
25%      2024.000000  1.060200e+05  106000.000000       0.000000
50%      2024.000000  1.470000e+05  146206.000000       0.000000
75%      2025.000000  1.990000e+05  198000.000000       0.000000
max      2025.000000  3.040000e+07  800000.000000     100.000000

In [ ]:
df.shape

(133349, 11)

In [ ]:
linhas, colunas = df.shape[0], df.shape[1]
print('linhas:', linhas)
print('colunas:', colunas)

linhas: 133349
colunas: 11


In [ ]:
df.columns

Index(['work_year', 'experience_level', 'employment_type', 'job_title',
       'salary', 'salary_currency', 'salary_in_usd', 'employee_residence',
       'remote_ratio', 'company_location', 'company_size'],
      dtype='object')

In [ ]:
# Traduzir nomes das colunas para português
df.columns = ['ano_trabalho', 'nivel_experiencia', 'tipo_emprego', 'cargo',
              'salario', 'moeda_salario', 'salario_em_usd', 'residencia_empregado',
              'proporcao_remoto', 'localizacao_empresa', 'tamanho_empresa']

# Exibir os nomes das colunas traduzidas para verificar
display(df.columns)

Index(['ano_trabalho', 'nivel_experiencia', 'tipo_emprego', 'cargo', 'salario',
       'moeda_salario', 'salario_em_usd', 'residencia_empregado',
       'proporcao_remoto', 'localizacao_empresa', 'tamanho_empresa'],
      dtype='object')

In [ ]:
df['nivel_experiencia'].value_counts()

nivel_experiencia
SE    77241
MI    40465
EN    12443
EX     3200
Name: count, dtype: int64

In [ ]:
df['tipo_emprego'].value_counts()

tipo_emprego
FT    132563
CT       394
PT       376
FL        16
Name: count, dtype: int64

In [ ]:
df['proporcao_remoto'].value_counts()

proporcao_remoto
0      105312
100     27718
50        319
Name: count, dtype: int64

In [ ]:
df['tamanho_empresa'].value_counts()

tamanho_empresa
M    129561
L      3574
S       214
Name: count, dtype: int64

In [ ]:
# Mapear abreviações para nomes completos em português
mapeamento_nivel_experiencia = {
    'SE': 'Senior',
    'MI': 'Pleno',
    'EN': 'Junior',
    'EX': 'Executivo'
}

# Aplicar o mapeamento à coluna 'nivel_experiencia'
df['nivel_experiencia'] = df['nivel_experiencia'].map(mapeamento_nivel_experiencia)

# Exibir os valores únicos para verificar
display(df['nivel_experiencia'].unique())

array([nan], dtype=object)

In [ ]:
# Mapear abreviações para nomes completos em português
mapeamento_tipo_emprego = {
    'FT': 'Tempo Integral',
    'CT': 'Contrato',
    'PT': 'Tempo Parcial',
    'FL': 'Freelancer'
}

# Aplicar o mapeamento à coluna 'tipo_emprego'
df['tipo_emprego'] = df['tipo_emprego'].map(mapeamento_tipo_emprego)

# Exibir os valores únicos para verificar
display(df['tipo_emprego'].unique())

array([nan], dtype=object)

In [ ]:
# Mapear categorias numéricas para descrições em português
mapeamento_proporcao_remoto = {
    0: 'Presencial',
    50: 'Híbrido',
    100: 'Remoto'
}

# Aplicar o mapeamento à coluna 'proporcao_remoto'
df['proporcao_remoto'] = df['proporcao_remoto'].map(mapeamento_proporcao_remoto)

# Exibir os valores únicos para verificar
display(df['proporcao_remoto'].unique())

array([nan], dtype=object)

In [ ]:
df.head()

ano_trabalho nivel_experiencia tipo_emprego               cargo  salario  \
0        2025.0               NaN          NaN  Solutions Engineer   214000   
1        2025.0               NaN          NaN  Solutions Engineer   136000   
2        2025.0               NaN          NaN       Data Engineer   158800   
3        2025.0               NaN          NaN       Data Engineer   139200   
4        2025.0               NaN          NaN       Data Engineer    90000   

  moeda_salario  salario_em_usd residencia_empregado proporcao_remoto  \
0           USD          214000                   US              NaN   
1           USD          136000                   US              NaN   
2           USD          158800                   AU              NaN   
3           USD          139200                   AU              NaN   
4           USD           90000                   US              NaN   

  localizacao_empresa tamanho_empresa  
0                  US               M  
1                  US               M  
2                  AU               M  
3                  AU               M  
4                  US               M

In [ ]:
df.describe(include='object')

nivel_experiencia tipo_emprego           cargo moeda_salario  \
count                  0            0          133349        133349   
unique                 0            0             390            26   
top                  NaN          NaN  Data Scientist           USD   
freq                 NaN          NaN           17314        126140   

       residencia_empregado proporcao_remoto localizacao_empresa  \
count                133349                0              133349   
unique                  102                0                  95   
top                      US              NaN                  US   
freq                 119579              NaN              119641   

       tamanho_empresa  
count           133349  
unique               3  
top                  M  
freq            129561

#Aula 02 - Aprendendo a Limpar e Preparar os Dados

In [ ]:
df.isnull()

work_year  experience_level  employment_type  job_title  salary  \
0           False             False            False      False   False   
1           False             False            False      False   False   
2           False             False            False      False   False   
3           False             False            False      False   False   
4           False             False            False      False   False   
...           ...               ...              ...        ...     ...   
133344      False             False            False      False   False   
133345      False             False            False      False   False   
133346      False             False            False      False   False   
133347      False             False            False      False   False   
133348      False             False            False      False   False   

        salary_currency  salary_in_usd  employee_residence  remote_ratio  \
0                 False          False               False         False   
1                 False          False               False         False   
2                 False          False               False         False   
3                 False          False               False         False   
4                 False          False               False         False   
...                 ...            ...                 ...           ...   
133344            False          False               False         False   
133345            False          False               False         False   
133346            False          False               False         False   
133347            False          False               False         False   
133348            False          False               False         False   

        company_location  company_size  
0                  False         False  
1                  False         False  
2                  False         False  
3                  False         False  
4                  False         False  
...                  ...           ...  
133344             False         False  
133345             False         False  
133346             False         False  
133347             False         False  
133348             False         False  

[133349 rows x 11 columns]

In [ ]:
df.isnull().sum()

work_year             10
experience_level       0
employment_type        0
job_title              0
salary                 0
salary_currency        0
salary_in_usd          0
employee_residence     0
remote_ratio           0
company_location       0
company_size           0
dtype: int64

In [ ]:
df['work_year'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [ ]:
df[df.isnull().any(axis=1)]

work_year experience_level employment_type                  job_title  \
5588          NaN               SE              FT            Product Manager   
59692         NaN               MI              FT                   Engineer   
59710         NaN               EN              FT             Data Scientist   
59759         NaN               SE              FT          Software Engineer   
59789         NaN               SE              FT                   Engineer   
131000        NaN               SE              FT  Machine Learning Engineer   
131006        NaN               SE              FT     Data Analytics Manager   
133054        NaN               EN              FT             Data Scientist   
133281        NaN               MI              FT  Machine Learning Engineer   
133317        NaN               MI              FT             Data Scientist   

        salary salary_currency  salary_in_usd employee_residence  \
5588    184500             USD         184500                 US   
59692   110000             USD         110000                 DE   
59710   208800             USD         208800                 US   
59759   135000             USD         135000                 US   
59789   112000             USD         112000                 US   
131000  163800             USD         163800                 US   
131006  204500             USD         204500                 US   
133054   40000             USD          40000                 JP   
133281  180000             PLN          46597                 PL   
133317  130000             USD         130000                 US   

        remote_ratio company_location company_size  
5588               0               US            M  
59692              0               DE            M  
59710              0               US            M  
59759              0               US            M  
59789              0               US            M  
131000             0               US            M  
131006             0               US            M  
133054           100               MY            L  
133281           100               PL            L  
133317            50               US            L

In [ ]:
import numpy as np

df_salarios = pd.DataFrame({
    'none': ['Ana', 'Carlos', 'Bruno', 'Jorge'],
    'salario': [4000, np.nan, 5000, np.nan]
})

df_salarios['salary'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))
df_salarios

none  salario  salary
0     Ana   4000.0  4000.0
1  Carlos      NaN  4500.0
2   Bruno   5000.0  5000.0
3   Jorge      NaN  4500.0